import { CategoryWithItems } from "./models/CategoryWithItems";
import { MenuCategory } from "./models/MenuCategory";
import { MenuItem } from "./models/MenuItem";

export class AppService {
    findItem(restId: number, itemId: number): MenuItem {
        const rest = this.restaurants.find(r => r.id === restId)!;
        const menuItem = rest.menu?.find(item => item.itemId === itemId)!;
        return {
            id: menuItem.itemId,
            title: menuItem.itemTitle,
            price: menuItem.price,
            image: menuItem.img,
        };
    }
    getRestaurants(): { id: number, title: string, img: string }[] {
        return this.restaurants.map(r => ({
            id: r.id,
            title: r.title,
            img: r.img
        }));
    }

    getRestaurant(restId: number) {
        const rest = this.restaurants.find(r => r.id === restId)!;
        return { title: rest.title, img: rest.img };
    }

    getCategories(restId: number): MenuCategory[] {
        const rest = this.restaurants.find(r => r.id === restId)!;
        return rest.categories?.map(c => ({
            catId: c.catId,
            title: c.title,
        })) ?? [];
    }

    getCategoriesWithItems(restId: number): CategoryWithItems[] {
        const restaurant = this.restaurants.find(r => r.id === restId);
        if (!restaurant) return [];
        if (!restaurant.categories) return [];
        const result: CategoryWithItems[] = [];

        for (let cat of restaurant.categories) {
            const catWithItems = new CategoryWithItems();
            result.push(catWithItems);
            catWithItems.catId = cat.catId;
            catWithItems.catTitle = cat.title;
            catWithItems.items = restaurant.menu
                .filter(item => item.categories.includes(cat.catId))
                .map(item => ({
                    id: item.itemId,
                    title: item.itemTitle,
                    price: item.price,
                    image: item.img,
                }));
        }

        return result;
    }

    public restaurants = [
        {
            id: 1,
            title: 'Burger King',
            img: 'https://eda.yandex/images/3490902/5ce3a8059f71e9de916f6a0c7eabe5ad-648x312.jpg',
            order: 'Order',
            categories: [
                {
                    catId: 1,
                    title: 'Burgers',
                },
                {
                    catId: 2,
                    title: 'Rolls',
                },
                {
                    catId: 3,
                    title: 'Fries',
                },
                {
                    catId: 4,
                    title: 'Lemonades',
                },
                {
                    catId: 5,
                    title: 'Hot-Drinks',
                },
                {
                    catId: 6,
                    title: 'Desserts',
                },
            ],
            menu: [
                {
                    itemId: 1,
                    itemTitle: 'Cheeseburger',
                    price: 3.0,
                    img: 'https://tn.fishki.net/26/upload/post/2023/11/16/4524487/tn/1_f68153c8bd9a9c174a8be5acc78d7be2.png',
                    categories: [1],
                },
                {
                    itemId: 2,
                    itemTitle: 'Double Cheeseburger',
                    price: 4.0,
                    img: 'https://avatars.mds.yandex.net/i?id=f72f8b32ab5664565c6764216044ca94_l-5222115-images-thumbs&n=13',
                    categories: [1],
                },
                {
                    itemId: 3,
                    itemTitle: 'Whopper',
                    price: 6.0,
                    img: 'https://assets.faceit-cdn.net/teams_avatars/cb19a267-c420-46cd-8caa-ad29e443b05c_1550758264630.jpg',
                    categories: [1],
                },
                {
                    itemId: 4,
                    itemTitle: 'Hamburger',
                    price: 2.50,
                    img: 'https://www.m24.ru/b/d/nBkSUhL2hFUun8m2Ir6BrNOp2Z318Ji-mifGnuWR9mOBdDebBizCnTY8qdJf6ReJ58vU9meMMok3Ee2nhSR6ISeO9G1N_wjJ=IrAOBOHuijDMLdKLEnmK8w.jpg',
                    categories: [1],
                },
                {
                    itemId: 5,
                    itemTitle: 'Spicy Chicken Burger',
                    price: 6.0,
                    img: 'https://miro.medium.com/v2/resize:fit:1000/1*kI2IsBRTQyc3uYSeJnPgzA.jpeg',
                    categories: [1],
                },
                {
                    itemId: 8,
                    itemTitle: 'Crispy Chicken Burger',
                    price: 5.0,
                    img: 'https://static.vecteezy.com/system/resources/previews/030/353/845/non_2x/crispy-chicken-burger-ai-generated-photo.jpg',
                    categories: [1],
                },
                {
                    itemId: 13,
                    itemTitle: 'Philadelphia Roll',
                    price: 10.0,
                    img: 'https://img.dasreda.ru/photo-data/864b9971-21fd-42eb-bff4-300e55cb1ab6/shutterstock_1578894298.jpg',
                    categories: [2],
                },
                {
                    itemId: 18,
                    itemTitle: 'Crunchy Dragon Roll',
                    price: 12.0,
                    img: 'https://imageproxy.wolt.com/menu/menu-images/62f29a408d874311ed6b0088/d235a226-61a2-11ed-a4ef-eef424720c3a_crunchy_rolls_california_maki_rolls_vegan_8d0c4850df2d27f08c7e9b444bef05c1_1280_q60.jpeg',
                    categories: [2],
                },
                {
                    itemId: 19,
                    itemTitle: 'Shrimp Tempura Roll',
                    price: 12.0,
                    img: 'https://static.tildacdn.com/tild3362-3965-4037-b031-326134613739/___.jpg',
                    categories: [2],
                },
                {
                    itemId: 23,
                    itemTitle: 'Dragon Roll',
                    price: 15.0,
                    img: 'https://imageproxy.wolt.com/assets/67b699a12501ae1129add431',
                    categories: [2],
                },
                {
                    itemId: 24,
                    itemTitle: 'Black Mamba Roll',
                    price: 16.0,
                    img: 'https://sushi-jet.ru/wa-data/public/shop/products/82/03/382/images/3088/3088.1400x0.jpg',
                    categories: [2],
                },
                {
                    itemId: 25,
                    itemTitle: 'Truffle Salmon Roll',
                    price: 16.0,
                    img: 'https://www.kikkoman.eu/fileadmin/_processed_/0/f/csm_1025-recipe-page-Spicy-tuna-and-salmon-rolls_desktop_b6172c0072.jpg',
                    categories: [2],
                },
                {
                    itemId: 27,
                    itemTitle: 'French Fries',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=f60d11b7f133fb988ed2046d9c21634d_l-5451037-images-thumbs&n=13',
                    categories: [3],
                },
                {
                    itemId: 30,
                    itemTitle: 'Waffle Fries',
                    price: 4.0,
                    img: 'https://s.yimg.com/ny/api/res/1.2/0Jt0mp_eonOrfEHo75FhOA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/chowhound_739/b4263c6a465c37f1652ea0da7cd647b5',
                    categories: [3],
                },
                {
                    itemId: 31,
                    itemTitle: 'Curly Fries',
                    price: 4.0,
                    img: 'https://www.tastingtable.com/img/gallery/the-clever-hack-to-get-curly-fries-without-a-spiralizer/l-intro-1649691299.jpg',
                    categories: [3],
                },
                {
                    itemId: 33,
                    itemTitle: 'Chili Cheese Fries',
                    price: 7.0,
                    img: 'https://waybackburgers.com/cdn-cgi/imagedelivery/7ZWWcce1zV6LWjfueUGVJg/waybackburgers.com/ChiliCheeseFries_Featured.jpg/w=9999',
                    categories: [3],
                },
                {
                    itemId: 37,
                    itemTitle: 'Sweet Potato Fries',
                    price: 5.0,
                    img: 'https://as1.ftcdn.net/jpg/01/13/71/16/1000_F_113711679_iY9e1dKwndn73poCp6EEk2TOCE8AVU94.jpg',
                    categories: [3],
                },
                {
                    itemId: 38,
                    itemTitle: 'Tater Tots',
                    price: 6.0,
                    img: 'https://avatars.dzeninfra.ru/get-zen_doc/108872/pub_5b8406ae0db7b300aa002c92_5b843b2847174c00aab185be/scale_1200',
                    categories: [3],
                },
                {
                    itemId: 43,
                    itemTitle: 'Orange juice',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ed38fefcfa485a4389526d9e0dd8b691_l-5679112-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 44,
                    itemTitle: 'Fanta',
                    price: 1.5,
                    img: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/57680392120413.5e432bbe9f19d.jpg',
                    categories: [4],
                },
                {
                    itemId: 45,
                    itemTitle: 'Sprite',
                    price: 2.0,
                    img: 'https://i.pinimg.com/originals/89/c3/83/89c38360cc86e0100c5d5a4a14b909ba.jpg',
                    categories: [4],
                },
                {
                    itemId: 55,
                    itemTitle: 'English Tea',
                    price: 3.0,
                    img: 'https://www.picnic-catering.ru/wp-content/uploads/2020/06/chaj-paketirovannyj-1.jpg',
                    categories: [5],
                },
                {
                    itemId: 46,
                    itemTitle: 'Americano',
                    price: 3.0,
                    img: 'https://galata-restaurant.ru/wp-content/uploads/2022/11/kofe-i-kofejnye-zerna.jpg',
                    categories: [5],
                },
                {
                    itemId: 47,
                    itemTitle: 'Latte',
                    price: 4.0,
                    img: 'https://i.pinimg.com/originals/0b/49/fb/0b49fbf251a53ff097fe2cf3eded7545.jpg',
                    categories: [5],
                },
                {
                    itemId: 48,
                    itemTitle: 'Cappuccino',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=1caa8d5782bbb457d3e6c5c004ce387e_l-2480510-images-thumbs&n=13',
                    categories: [5],
                },
                {
                    itemId: 62,
                    itemTitle: 'Red Velvet Cake',
                    price: 8.0,
                    img: 'https://avatars.mds.yandex.net/i?id=71097f648301335bb04dec6700b6ebfd_l-5887216-images-thumbs&n=13',
                    categories: [6],
                },
                {
                    itemId: 63,
                    itemTitle: 'Carrot Cake',
                    price: 7.0,
                    img: 'https://image.winudf.com/v2/image1/Y29tLndhbGxwYXBlcnNoYWxsLmNha2UxX3NjcmVlbl82XzE2MzQzMTg2MzBfMDUy/screen-6.jpg?fakeurl=1&type=.jpg',
                    categories: [6],
                },
                {
                    itemId: 64,
                    itemTitle: 'Ice Cream Waffle Bowl',
                    price: 7.5,
                    img: 'https://xoxobella.com/wp-content/uploads/2022/06/easy_brownie_sundae_waffle_bowls-054.jpg',
                    categories: [6],
                },
                {
                    itemId: 66,
                    itemTitle: 'Cinnamon Roll',
                    price: 3.0,
                    img: 'https://sun9-31.userapi.com/impg/dpGBX0GfGFHcDP35M73CaG2SL-wMCS3hJYCf_A/xxgaoyQv158.jpg?size=930x620&quality=96&sign=4bba8b41d92adffc0ff39195a65dd8c5&type=album',
                    categories: [6],
                },
            ],
        },
        {
            id: 2,
            title: 'KFC',
            img: 'https://eda.yandex/images/3772784/363315778e80282c639d899dfc8819e4-648x312.jpg',
            order: 'Order',
            categories: [
                {
                    catId: 1,
                    title: 'Burgers',
                },
                {
                    catId: 7,
                    title: 'Chicken',
                },
                {
                    catId: 3,
                    title: 'Fries',
                },
                {
                    catId: 4,
                    title: 'Lemonades',
                },
                {
                    catId: 5,
                    title: 'Hot-Drinks',
                },
                {
                    catId: 6,
                    title: 'Desserts',
                },
            ],
            menu: [
                {
                    itemId: 1,
                    itemTitle: 'Cheeseburger',
                    price: 3.0,
                    img: 'https://tn.fishki.net/26/upload/post/2023/11/16/4524487/tn/1_f68153c8bd9a9c174a8be5acc78d7be2.png',
                    categories: [1],
                },
                {
                    itemId: 2,
                    itemTitle: 'Double Cheeseburger',
                    price: 4.0,
                    img: 'https://avatars.mds.yandex.net/i?id=f72f8b32ab5664565c6764216044ca94_l-5222115-images-thumbs&n=13',
                    categories: [1],
                },
                {
                    itemId: 3,
                    itemTitle: 'Whopper',
                    price: 6.0,
                    img: 'https://assets.faceit-cdn.net/teams_avatars/cb19a267-c420-46cd-8caa-ad29e443b05c_1550758264630.jpg',
                    categories: [1],
                },
                {
                    itemId: 4,
                    itemTitle: 'Hamburger',
                    price: 2.50,
                    img: 'https://www.m24.ru/b/d/nBkSUhL2hFUun8m2Ir6BrNOp2Z318Ji-mifGnuWR9mOBdDebBizCnTY8qdJf6ReJ58vU9meMMok3Ee2nhSR6ISeO9G1N_wjJ=IrAOBOHuijDMLdKLEnmK8w.jpg',
                    categories: [1],
                },
                {
                    itemId: 68,
                    itemTitle: 'Hot & Spicy Wings',
                    price: 6.0,
                    img: 'https://i.pinimg.com/originals/e8/73/b6/e873b6806423847fb8a3a4cff9be50d3.jpg',
                    categories: [7],
                },
                {
                    itemId: 69,
                    itemTitle: 'Crispy Chicken Tenders',
                    price: 6.5,
                    img: 'https://avatars.mds.yandex.net/i?id=04d92a01f204f9a3d876cb98d2ce1dab_l-5192502-images-thumbs&n=13',
                    categories: [7],
                },
                {
                    itemId: 70,
                    itemTitle: 'Bucket for Friends',
                    price: 6.5,
                    img: 'https://www.kfc-suisse.ch/fileadmin/_processed_/6/d/csm_mood_original_bucket_716d606391.jpg',
                    categories: [7],
                },
                {
                    itemId: 43,
                    itemTitle: 'Orange juice',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ed38fefcfa485a4389526d9e0dd8b691_l-5679112-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 44,
                    itemTitle: 'Fanta',
                    price: 1.5,
                    img: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/57680392120413.5e432bbe9f19d.jpg',
                    categories: [4],
                },
                {
                    itemId: 45,
                    itemTitle: 'Sprite',
                    price: 2.0,
                    img: 'https://i.pinimg.com/originals/89/c3/83/89c38360cc86e0100c5d5a4a14b909ba.jpg',
                    categories: [4],
                },
                {
                    itemId: 55,
                    itemTitle: 'English Tea',
                    price: 3.0,
                    img: 'https://www.picnic-catering.ru/wp-content/uploads/2020/06/chaj-paketirovannyj-1.jpg',
                    categories: [5],
                },
                {
                    itemId: 47,
                    itemTitle: 'Latte',
                    price: 4.0,
                    img: 'https://i.pinimg.com/originals/0b/49/fb/0b49fbf251a53ff097fe2cf3eded7545.jpg',
                    categories: [5],
                },
                {
                    itemId: 48,
                    itemTitle: 'Cappuccino',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=1caa8d5782bbb457d3e6c5c004ce387e_l-2480510-images-thumbs&n=13',
                    categories: [5],
                },
                {
                    itemId: 27,
                    itemTitle: 'French Fries',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=f60d11b7f133fb988ed2046d9c21634d_l-5451037-images-thumbs&n=13',
                    categories: [3],
                },
                {
                    itemId: 29,
                    itemTitle: 'Bacon Cheese Fries',
                    price: 6.0,
                    img: 'https://www.cenariomt.com.br/wp-content/uploads/2023/10/Receita-de-batata-frita-com-cheddar.jpg',
                    categories: [3],
                },
                {
                    itemId: 30,
                    itemTitle: 'Waffle Fries',
                    price: 4.0,
                    img: 'https://s.yimg.com/ny/api/res/1.2/0Jt0mp_eonOrfEHo75FhOA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/chowhound_739/b4263c6a465c37f1652ea0da7cd647b5',
                    categories: [3],
                },
                {
                    itemId: 31,
                    itemTitle: 'Curly Fries',
                    price: 4.0,
                    img: 'https://www.tastingtable.com/img/gallery/the-clever-hack-to-get-curly-fries-without-a-spiralizer/l-intro-1649691299.jpg',
                    categories: [3],
                },
                {
                    itemId: 34,
                    itemTitle: 'Loaded Fries',
                    price: 8.0,
                    img: 'https://thumbs.dreamstime.com/b/double-portion-spicy-fries-beef-mince-potato-seasoned-chili-topping-melted-cheese-close-up-high-angle-two-forks-191885232.jpg',
                    categories: [3],
                },
                {
                    itemId: 35,
                    itemTitle: 'Spicy Buffalo Fries',
                    price: 7.0,
                    img: 'https://i.ytimg.com/vi/4nTesAViGqM/maxresdefault.jpg',
                    categories: [3],
                },
                {
                    itemId: 37,
                    itemTitle: 'Sweet Potato Fries',
                    price: 5.0,
                    img: 'https://as1.ftcdn.net/jpg/01/13/71/16/1000_F_113711679_iY9e1dKwndn73poCp6EEk2TOCE8AVU94.jpg',
                    categories: [3],
                },
                {
                    itemId: 38,
                    itemTitle: 'Tater Tots',
                    price: 6.0,
                    img: 'https://avatars.dzeninfra.ru/get-zen_doc/108872/pub_5b8406ae0db7b300aa002c92_5b843b2847174c00aab185be/scale_1200',
                    categories: [3],
                },
                {
                    itemId: 62,
                    itemTitle: 'Red Velvet Cake',
                    price: 8.0,
                    img: 'https://avatars.mds.yandex.net/i?id=71097f648301335bb04dec6700b6ebfd_l-5887216-images-thumbs&n=13',
                    categories: [6],
                },
                {
                    itemId: 63,
                    itemTitle: 'Carrot Cake',
                    price: 7.0,
                    img: 'https://image.winudf.com/v2/image1/Y29tLndhbGxwYXBlcnNoYWxsLmNha2UxX3NjcmVlbl82XzE2MzQzMTg2MzBfMDUy/screen-6.jpg?fakeurl=1&type=.jpg',
                    categories: [6],
                },
                {
                    itemId: 64,
                    itemTitle: 'Ice Cream Waffle Bowl',
                    price: 7.5,
                    img: 'https://xoxobella.com/wp-content/uploads/2022/06/easy_brownie_sundae_waffle_bowls-054.jpg',
                    categories: [6],
                },
            ],
        },
        {
            id: 3,
            title: 'Gan Bei',
            img: 'https://eda.yandex/images/2796335/1f85f1696ffd42259de282b73cb7af48-648x312.jpg',
            order: 'Order',
            categories: [
                {
                    catId: 1,
                    title: 'Asian Food',
                },
                {
                    catId: 2,
                    title: 'Vegetable Dishes',
                },
                {
                    catId: 3,
                    title: 'Salads',
                },
                {
                    catId: 4,
                    title: 'Soups',
                },
                {
                    catId: 5,
                    title: 'Fish Dishes',
                },
            ],
            menu: [
                {
                    itemId: 71,
                    itemTitle: 'Pad Thai',
                    price: 11.0,
                    img: 'https://i.pinimg.com/736x/3e/07/8c/3e078c4c6f4a84a8bbc0cd953b61fecc.jpg',
                    categories: [1],
                },
                {
                    itemId: 72,
                    itemTitle: 'Ramen',
                    price: 9.0,
                    img: 'https://www.tokyoweekender.com/wp-content/uploads/2024/03/shutterstock_1834868050.jpg',
                    categories: [1],
                },
                {
                    itemId: 73,
                    itemTitle: 'Gyoza',
                    price: 7.5,
                    img: 'https://cdn.nur.kz/images/1200x675/495868feac16cd91.jpeg',
                    categories: [1],
                },
                {
                    itemId: 74,
                    itemTitle: 'Bibimbap ',
                    price: 10.0,
                    img: 'https://avatars.mds.yandex.net/i?id=3374dbefa0fbedb02c7f89234bfc125feb92af27-4570299-images-thumbs&n=13',
                    categories: [1],
                },
                {
                    itemId: 75,
                    itemTitle: 'Sushi Combo',
                    price: 12.0,
                    img: 'https://i.pinimg.com/originals/85/cd/15/85cd15286b53a3e15cf31976d6ba3935.jpg',
                    categories: [1],
                },
                {
                    itemId: 76,
                    itemTitle: 'Grilled Veggie Plate',
                    price: 8.5,
                    img: 'https://v.wpimg.pl/NzYyMTY2YRs4GztndklsDntDbz0wEGJYLFt3dnYDfEJpAWIyMF4rCDwJIno-QDsKOA49eileYRspEGIiaB0qEyoJITUgHSsXOxwpe2sBfUk6HShidAd-TD1UeWRgC2NCYUl0eWxWKE1vS3xibwUtGHsE',
                    categories: [2],
                },
                {
                    itemId: 77,
                    itemTitle: 'Stuffed Bell Peppers',
                    price: 9.0,
                    img: 'https://i.pinimg.com/originals/7b/47/53/7b47539081a0ef18be5c81e1c6ed659f.jpg',
                    categories: [2],
                },
                {
                    itemId: 79,
                    itemTitle: 'Falafel Wrap',
                    price: 6.0,
                    img: 'https://i.ytimg.com/vi/LKXQkdo1_U0/maxresdefault.jpg',
                    categories: [2],
                },
                {
                    itemId: 80,
                    itemTitle: 'Vegetable Curry',
                    price: 8.0,
                    img: 'https://vietcafealmaty.kz/wp-content/uploads/2021/10/5aa1fa46-e04a-4aa0-9930-c8238ffc1fbb.jpeg',
                    categories: [2],
                },
                {
                    itemId: 85,
                    itemTitle: 'Quinoa Salad',
                    price: 9.0,
                    img: 'https://i.pinimg.com/originals/09/6c/6d/096c6d87e065dd9e22eb870c79f6a92e.jpg',
                    categories: [2],
                },
                {
                    itemId: 86,
                    itemTitle: 'Greek Salad',
                    price: 6.0,
                    img: 'https://scdn.chibbis.ru/live/products/8509ef6c3420e8494ee110991e351f4f.jpeg',
                    categories: [3],
                },
                {
                    itemId: 87,
                    itemTitle: 'Caesar Salad',
                    price: 7.5,
                    img: 'https://s.yimg.com/ny/api/res/1.2/Ti6jdt1N_r8l.kSwEgX5xg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/tasting_table_543/2cb242634400b64ae15db6647ec2813d',
                    categories: [3],
                },
                {
                    itemId: 88,
                    itemTitle: 'Asian Slaw',
                    price: 8.0,
                    img: 'https://hips.hearstapps.com/hmg-prod/images/delish-230313-23-thai-style-slaw-1985-eb-index-64251529cd4e0.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*',
                    categories: [3],
                },
                {
                    itemId: 89,
                    itemTitle: 'Caprese Salad',
                    price: 8.2,
                    img: 'https://s.yimg.com/ny/api/res/1.2/.R5t0cm0Orh0x1ALJzJusg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02Nzc-/https://media.zenfs.com/en/chowhound_739/bc382b55f30c34029fd950d6dce10658',
                    categories: [3],
                },
                {
                    itemId: 90,
                    itemTitle: 'Tom Yum',
                    price: 8.4,
                    img: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1wUIz4.img?w=1600&h=900&m=4&q=79',
                    categories: [4],
                },
                {
                    itemId: 91,
                    itemTitle: 'Minestrone',
                    price: 4.8,
                    img: 'https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_662160f82d4e14129540be22_662161ab824b084ed774ffd2/scale_1200',
                    categories: [4],
                },
                {
                    itemId: 92,
                    itemTitle: 'MineLentil Soupstrone',
                    price: 4.8,
                    img: 'https://s.yimg.com/ny/api/res/1.2/SmllJqFw._MQOGIWdByC0Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTQ4MA--/https://media.zenfs.com/en/delish_597/6b448520ec11a21fc2f130e5729723c1',
                    categories: [4],
                },
                {
                    itemId: 93,
                    itemTitle: 'Miso Soup',
                    price: 5.0,
                    img: 'https://i.pinimg.com/originals/00/fc/1c/00fc1c69f0dacc297b0876d18490f18a.jpg',
                    categories: [4],
                },
                {
                    itemId: 94,
                    itemTitle: 'Creamy Mushroom Soup',
                    price: 6.8,
                    img: 'https://avatars.mds.yandex.net/i?id=17d99378b864da5b958800dba14c59a7_l-5222088-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 95,
                    itemTitle: 'Grilled Salmon',
                    price: 13.1,
                    img: 'https://avatars.mds.yandex.net/i?id=5fa66d3fc0831b9065da401e348727a46476d907-4288990-images-thumbs&n=13',
                    categories: [5],
                },
                {
                    itemId: 96,
                    itemTitle: 'Fish & Chips',
                    price: 14.0,
                    img: 'https://cdn.lifehacker.ru/wp-content/uploads/2024/03/303_1711123887.jpg',
                    categories: [5],
                },
                {
                    itemId: 97,
                    itemTitle: 'Garlic Butter Shrimp',
                    price: 16.5,
                    img: 'https://i.ytimg.com/vi/t-xM807ZV6w/maxresdefault.jpg',
                    categories: [5],
                },
                {
                    itemId: 98,
                    itemTitle: 'Seafood Paella',
                    price: 23.7,
                    img: 'https://www.unileverfoodsolutions.ca/dam/global-ufs/mcos/nam/ufs-website/article-page/1260x741_Paella.jpg',
                    categories: [5],
                },
                {
                    itemId: 102,
                    itemTitle: 'Scallops with Risotto',
                    price: 23.7,
                    img: 'https://i.ytimg.com/vi/TdyeTK-hJhA/maxresdefault.jpg',
                    categories: [5],
                },
            ]
        },
        {
            id: 4,
            title: 'Gusto',
            img: 'https://eda.yandex/images/14790567/74a2344d71b04e1b96d9437cdd59a37c-648x312.jpg',
            order: 'Order',
            menu: [
                {
                    itemId: 59,
                    itemTitle: 'Chocolate Brownie',
                    price: 5.0,
                    img: 'https://i.pinimg.com/736x/9a/8a/70/9a8a70a736535b1143dfdffd2eb84f71.jpg',
                    categories: [6],
                },
                {
                    itemId: 60,
                    itemTitle: 'New York Cheesecake',
                    price: 6.0,
                    img: 'https://i2.wp.com/www.thespruceeats.com/thmb/W-Ur-ceUIwo0XLyBPzT2VwcwgJU=/1500x1000/filters:fill(auto,1)/gluten-free-new-york-cheesecake-1450985-hero-01-dc54f9daf38044238b495c7cefc191fa.jpg',
                    categories: [6],
                },
                {
                    itemId: 61,
                    itemTitle: 'Chocolate Chip Cookies',
                    price: 2.0,
                    img: 'https://i.ytimg.com/vi/rYPfkR9d3f8/maxresdefault.jpg',
                    categories: [6],
                },
                {
                    itemId: 62,
                    itemTitle: 'Red Velvet Cake',
                    price: 8.0,
                    img: 'https://avatars.mds.yandex.net/i?id=71097f648301335bb04dec6700b6ebfd_l-5887216-images-thumbs&n=13',
                    categories: [6],
                },
                {
                    itemId: 63,
                    itemTitle: 'Carrot Cake',
                    price: 7.0,
                    img: 'https://image.winudf.com/v2/image1/Y29tLndhbGxwYXBlcnNoYWxsLmNha2UxX3NjcmVlbl82XzE2MzQzMTg2MzBfMDUy/screen-6.jpg?fakeurl=1&type=.jpg',
                    categories: [6],
                },
                {
                    itemId: 64,
                    itemTitle: 'Ice Cream Waffle Bowl',
                    price: 7.5,
                    img: 'https://xoxobella.com/wp-content/uploads/2022/06/easy_brownie_sundae_waffle_bowls-054.jpg',
                    categories: [6],
                },
                {
                    itemId: 65,
                    itemTitle: 'Sundae',
                    price: 4.0,
                    img: 'https://avatars.mds.yandex.net/i?id=29611f7f0fb039b4e7062e0f96a3a19d_l-12421862-images-thumbs&n=13',
                    categories: [6],
                },
                {
                    itemId: 66,
                    itemTitle: 'Cinnamon Roll',
                    price: 3.0,
                    img: 'https://sun9-31.userapi.com/impg/dpGBX0GfGFHcDP35M73CaG2SL-wMCS3hJYCf_A/xxgaoyQv158.jpg?size=930x620&quality=96&sign=4bba8b41d92adffc0ff39195a65dd8c5&type=album',
                    categories: [6],
                },
                {
                    itemId: 41,
                    itemTitle: 'Classic Coca Cola',
                    price: 2.0,
                    img: 'https://avatars.mds.yandex.net/i?id=2f5bb3061de77aa4fb9630c3ad5549cd_l-5235971-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 42,
                    itemTitle: 'Berry Blast Soda',
                    price: 2.5,
                    img: 'https://images.ctfassets.net/tlircn1cnxbm/586HcZ1G00A3CvHovLeadO/5f8f89c7a1f1cfcbeb2f2b4a4a3ee702/ice-encore-berry-blast_desktop_fr.jpg',
                    categories: [4],
                },
                {
                    itemId: 43,
                    itemTitle: 'Orange juice',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ed38fefcfa485a4389526d9e0dd8b691_l-5679112-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 44,
                    itemTitle: 'Fanta',
                    price: 1.5,
                    img: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/57680392120413.5e432bbe9f19d.jpg',
                    categories: [4],
                },
                {
                    itemId: 45,
                    itemTitle: 'Sprite',
                    price: 2.0,
                    img: 'https://i.pinimg.com/originals/89/c3/83/89c38360cc86e0100c5d5a4a14b909ba.jpg',
                    categories: [4],
                },
                {
                    itemId: 112,
                    itemTitle: 'Margherita',
                    price: 13.0,
                    img: 'https://i.pinimg.com/originals/01/e9/73/01e9735775861223f7bd76af6e3543dd.jpg',
                    categories: [15],
                },
                {
                    itemId: 113,
                    itemTitle: 'Pepperoni',
                    price: 14.3,
                    img: 'https://avatars.mds.yandex.net/i?id=d4380b44d6f043f8a378a9f8f8002773_l-12322312-images-thumbs&n=13',
                    categories: [15],
                },
                {
                    itemId: 114,
                    itemTitle: 'Hawaiian',
                    price: 11.9,
                    img: 'https://i.pinimg.com/736x/2d/15/00/2d15009cab2b7b82d880d6831cb45523.jpg',
                    categories: [15],
                },
                {
                    itemId: 115,
                    itemTitle: 'Truffle Mushroom',
                    price: 16.0,
                    img: 'https://avatars.mds.yandex.net/i?id=dc1bb0894277a7484e9edd2db1cce2cc_l-12911696-images-thumbs&n=13',
                    categories: [15],
                },
                {
                    itemId: 116,
                    itemTitle: 'Prosciutto e Rucola',
                    price: 20.0,
                    img: 'https://avatars.mds.yandex.net/i?id=5fc409c01ea9ffc84163cc61e0124846_l-5252675-images-thumbs&n=13',
                    categories: [15],
                },
                {
                    itemId: 117,
                    itemTitle: 'BBQ Chicken',
                    price: 14.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ffdacd53334e81a46ae0adf51db78ec3_l-5869007-images-thumbs&n=13',
                    categories: [15],
                },
                {
                    itemId: 118,
                    itemTitle: 'Diavola',
                    price: 13.5,
                    img: 'https://res.cloudinary.com/norgesgruppen/image/upload/c_fill,f_auto,h_630,q_auto:eco,w_1200/axcdfcfmyahxjmmj99pe.jpg',
                    categories: [15],
                },
                {
                    itemId: 119,
                    itemTitle: 'Seafood Pizza',
                    price: 21.2,
                    img: 'https://avatars.mds.yandex.net/i?id=323602a49f9d238be028275011bff0639e108e55-5616376-images-thumbs&n=13',
                    categories: [15],
                },
                {
                    itemId: 120,
                    itemTitle: 'Veggie Delight',
                    price: 15.7,
                    img: 'https://images.squarespace-cdn.com/content/v1/5a54f99cbe42d6754cfa6eec/1614793824893-JQRNIM98QO7SXB3OVEMZ/_3lZc3bw.jpeg',
                    categories: [15],
                },
                {
                    itemId: 121,
                    itemTitle: 'Caprese Pizza',
                    price: 18.6,
                    img: 'https://i.pinimg.com/originals/eb/d4/ad/ebd4ade0c563711c60c0e94049b654ab.jpg',
                    categories: [15],
                },
                {
                    itemId: 122,
                    itemTitle: 'Spaghetti Carbonara',
                    price: 15.8,
                    img: 'https://avatars.mds.yandex.net/i?id=a14f766ef68c40a5de57679544818712_l-5341398-images-thumbs&n=13',
                    categories: [16],
                },
                {
                    itemId: 123,
                    itemTitle: 'Penne Arrabbiata',
                    price: 12.0,
                    img: 'https://wums.ru/wp-content/uploads/2018/11/Arabyata-pasta-recept-1.jpg',
                    categories: [16],
                },
                {
                    itemId: 124,
                    itemTitle: 'Fettuccine Alfredo',
                    price: 17.9,
                    img: 'https://s.yimg.com/ny/api/res/1.2/46YdIHoQ9g_FoR9HBPv0ug--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzI-/https://media.zenfs.com/en/chowhound_739/ed6e65e591c36aab13a6dc6ca754331e',
                    categories: [16],
                },
                {
                    itemId: 125,
                    itemTitle: 'Linguine alle Vongole',
                    price: 22.4,
                    img: 'https://avatars.mds.yandex.net/i?id=f2f5f13fea299a253ba40d3e11bf2400f3619e63-8972573-images-thumbs&n=13',
                    categories: [16],
                },
                {
                    itemId: 126,
                    itemTitle: 'Pasta con Gamberi',
                    price: 16.8,
                    img: 'https://i.pinimg.com/originals/2c/fc/e2/2cfce29c409accca6fccb12d51a7ce18.jpg',
                    categories: [16],
                },
                {
                    itemId: 127,
                    itemTitle: 'Pasta Primavera',
                    price: 25.3,
                    img: 'https://avatars.mds.yandex.net/i?id=ddb95ad053b75de4275138de9a416e3d-4230909-images-thumbs&n=13',
                    categories: [16],
                },
                {
                    itemId: 128,
                    itemTitle: 'Truffle Mushroom Pasta',
                    price: 19.0,
                    img: 'https://mixnews.lv/wp-content/uploads/2024/07/14/2024-07-14-mixnews-truffle-mushroom-pasta-5.jpg',
                    categories: [16],
                },
            ]
        },
        {
            id: 5,
            title: 'Kebab Town',
            img: 'https://eda.yandex/images/3528150/a1b962fbe92a0e8affa04061fb957935-648x312.jpg',
            order: 'Order',
            menu: [
                {
                    itemId: 12,
                    itemTitle: 'California Roll',
                    price: 11.0,
                    img: 'https://s.yimg.com/ny/api/res/1.2/ossXgeRgKQLjzs86vW77wQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/chowhound_739/ea0a38727af9d30c280dee972edcb7bc',
                    categories: [2],
                },
                {
                    itemId: 13,
                    itemTitle: 'Philadelphia Roll',
                    price: 10.0,
                    img: 'https://img.dasreda.ru/photo-data/864b9971-21fd-42eb-bff4-300e55cb1ab6/shutterstock_1578894298.jpg',
                    categories: [2],
                },
                {
                    itemId: 14,
                    itemTitle: 'Dynamite Roll',
                    price: 9.0,
                    img: 'https://avatars.mds.yandex.net/i?id=81e2529f53a6727a43a063310ac99ac8_l-4055439-images-thumbs&n=13',
                    categories: [2],
                },
                {
                    itemId: 15,
                    itemTitle: 'Rainbow Roll',
                    price: 11.0,
                    img: 'https://avatars.mds.yandex.net/get-altay/2004078/2a00000184ac0a007bc80d9537581b9e6fbb/orig',
                    categories: [2],
                },
                {
                    itemId: 16,
                    itemTitle: 'Salmon Lover Roll',
                    price: 10.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ebe3d10cfc0aa27dad946e3e9e939c9c_l-4372511-images-thumbs&n=13',
                    categories: [2],
                },
                {
                    itemId: 17,
                    itemTitle: 'Tuna Crunch Roll',
                    price: 11.0,
                    img: 'https://avatars.mds.yandex.net/i?id=505cbdb2239ed6115129ff967129b162_l-12475310-images-thumbs&n=13',
                    categories: [2],
                },
                {
                    itemId: 18,
                    itemTitle: 'Crunchy Dragon Roll',
                    price: 12.0,
                    img: 'https://imageproxy.wolt.com/menu/menu-images/62f29a408d874311ed6b0088/d235a226-61a2-11ed-a4ef-eef424720c3a_crunchy_rolls_california_maki_rolls_vegan_8d0c4850df2d27f08c7e9b444bef05c1_1280_q60.jpeg',
                    categories: [2],
                },
                {
                    itemId: 19,
                    itemTitle: 'Shrimp Tempura Roll',
                    price: 12.0,
                    img: 'https://static.tildacdn.com/tild3362-3965-4037-b031-326134613739/___.jpg',
                    categories: [2],
                },
                {
                    itemId: 20,
                    itemTitle: 'Spider Roll',
                    price: 13.0,
                    img: 'https://i0.wp.com/popmenucloud.com/cdn-cgi/image/width=1920,height=1920,format=auto,fit=scale-down/izdtfxbo/c6830e4f-8d8c-41e2-b149-34899b7012fe.jpg?ssl=1',
                    categories: [2],
                },
                {
                    itemId: 21,
                    itemTitle: 'Volcano Roll',
                    price: 14.0,
                    img: 'https://avatars.mds.yandex.net/i?id=012ab35660de314796572667b99585a921c637b8-12416107-images-thumbs&n=13',
                    categories: [2],
                },
                {
                    itemId: 22,
                    itemTitle: 'Fire Roll',
                    price: 12.0,
                    img: 'https://avatars.mds.yandex.net/get-mpic/5210379/img_id295341660390599659.jpeg/9',
                    categories: [2],
                },
                {
                    itemId: 23,
                    itemTitle: 'Dragon Roll',
                    price: 15.0,
                    img: 'https://imageproxy.wolt.com/assets/67b699a12501ae1129add431',
                    categories: [2],
                },
                {
                    itemId: 24,
                    itemTitle: 'Black Mamba Roll',
                    price: 16.0,
                    img: 'https://sushi-jet.ru/wa-data/public/shop/products/82/03/382/images/3088/3088.1400x0.jpg',
                    categories: [2],
                },
                {
                    itemId: 25,
                    itemTitle: 'Truffle Salmon Roll',
                    price: 16.0,
                    img: 'https://www.kikkoman.eu/fileadmin/_processed_/0/f/csm_1025-recipe-page-Spicy-tuna-and-salmon-rolls_desktop_b6172c0072.jpg',
                    categories: [2],
                },
                {
                    itemId: 26,
                    itemTitle: 'Avocado Mango Roll',
                    price: 17.0,
                    img: 'https://avatars.mds.yandex.net/get-altay/939994/2a0000018635ce07e8bf714082f86f07544b/XXL_height',
                    categories: [2],
                },
                {
                    itemId: 41,
                    itemTitle: 'Classic Coca Cola',
                    price: 2.0,
                    img: 'https://avatars.mds.yandex.net/i?id=2f5bb3061de77aa4fb9630c3ad5549cd_l-5235971-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 42,
                    itemTitle: 'Berry Blast Soda',
                    price: 2.5,
                    img: 'https://images.ctfassets.net/tlircn1cnxbm/586HcZ1G00A3CvHovLeadO/5f8f89c7a1f1cfcbeb2f2b4a4a3ee702/ice-encore-berry-blast_desktop_fr.jpg',
                    categories: [4],
                },
                {
                    itemId: 43,
                    itemTitle: 'Orange juice',
                    price: 3.0,
                    img: 'https://avatars.mds.yandex.net/i?id=ed38fefcfa485a4389526d9e0dd8b691_l-5679112-images-thumbs&n=13',
                    categories: [4],
                },
                {
                    itemId: 44,
                    itemTitle: 'Fanta',
                    price: 1.5,
                    img: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/57680392120413.5e432bbe9f19d.jpg',
                    categories: [4],
                },
                {
                    itemId: 45,
                    itemTitle: 'Sprite',
                    price: 2.0,
                    img: 'https://i.pinimg.com/originals/89/c3/83/89c38360cc86e0100c5d5a4a14b909ba.jpg',
                    categories: [4],
                },
                {
                    itemId: 129,
                    itemTitle: 'Classic Chicken Shawarma',
                    price: 8.0,
                    img: 'https://i.ytimg.com/vi/91JF4ioJMXA/maxresdefault.jpg',
                    categories: [17],
                },
                {
                    itemId: 130,
                    itemTitle: 'Beef Doner Kebab',
                    price: 7.1,
                    img: 'https://avatars.mds.yandex.net/i?id=0273ca535abf072d1d643c33b51c72ed_l-5232350-images-thumbs&n=13',
                    categories: [17],
                },
                {
                    itemId: 131,
                    itemTitle: 'Falafel Wrap',
                    price: 8.0,
                    img: 'https://i.ytimg.com/vi/91JF4ioJMXA/maxresdefault.jpg',
                    categories: [17],
                },
                {
                    itemId: 132,
                    itemTitle: 'Classic Chicken Shawarma',
                    price: 7.5,
                    img: 'https://i.ytimg.com/vi/91JF4ioJMXA/maxresdefault.jpg',
                    categories: [17],
                },
            ]
        },
        {
            id: 6,
            title: 'Pho Bo',
            img: 'https://eda.yandex/images/3490335/a20cc5a68ecc40f0a6d183015f17565b-648x312.jpg',
            order: 'Order',
        },
        {
            id: 7,
            title: 'Tasty Food',
            img: 'https://eda.yandex/images/3456802/bd9872fe9fe230e270ae4b44ae938b0e-648x312.jpg',
            order: 'Order',
        },
        {
            id: 8,
            title: 'Formosa Bubble Tea',
            img: 'https://eda.yandex/images/3534679/a63bbaba7acbf91fb1ed3c336f2223b6-648x312.jpg',
            order: 'Order',
        },
        {
            id: 9,
            title: 'Ajia',
            img: 'https://eda.yandex/images/2794391/7a3602bf878a446c9b46e0d0b234a619-648x312.jpg',
            order: 'Order',
        },
        {
            id: 10,
            title: 'Phu Quoc',
            img: 'https://eda.yandex/images/3813301/84ca91f50d285a9fc7f94d32a7ff5a41-648x312.jpg',
            order: 'Order',
        },
        {
            id: 11,
            title: 'Pizza Yolo',
            img: 'https://eda.yandex/images/3518584/d38679646bbbc39e41353ab40259c92e-648x312.jpg',
            order: 'Order',
        },
        {
            id: 12,
            title: 'Veg Harmony Cafe',
            img: 'https://eda.yandex/images/13873613/bdbba0113f0d497b99d7d4d8503e401d-648x312.jpg',
            order: 'Order',
        },
        {
            id: 13,
            title: 'Mangal Master',
            img: 'https://eda.yandex/images/1463280/87b1d262880253815e88ebe158500a34-648x312.jpeg',
            order: 'Order',
        },
        {
            id: 14,
            title: 'Cheezus',
            img: 'https://eda.yandex/images/3490335/8ed66b0c9b794ab9876f6e25e5ab00ff-648x312.jpg',
            order: 'Order',
        },
        {
            id: 14,
            title: 'Fork',
            img: 'https://eda.yandex/images/3808326/004ac9002723d63c05c1e6620c1671db-648x312.jpg',
            order: 'Order',
        },
        {
            id: 14,
            title: 'Grill Kebab BBQ',
            img: 'https://eda.yandex/images/13802765/520cb74adc264a2a91e6cce36246e132-648x312.jpg',
            order: 'Order',
        },
    ];
}